export const CONFIG = {
  COLUMN_MAPPING: {
    '番号': 'ID',
    '種別': 'Type',
    '座標数': 'Coord_count',
    '有効性': 'Valid',
    '直線速度[μm/秒]': 'VSL',
    '曲線速度[μm/秒]': 'VCL',
    '平均速度[μm/秒]': 'VAP',
    '直進性': 'STR',
    '直線性': 'LIN',
    '頭部振幅[μm]': 'ALH',
    '頭部振動数[Hz]': 'BCF',
    '曲線性': 'WOB',
  },
  MOTILE_TYPE: 99,
  ALL_CASA_PARAMS: ['VCL', 'VSL', 'VAP', 'LIN', 'STR', 'WOB', 'ALH', 'BCF'],
  TSNE_FEATURES: ['VCL', 'VSL', 'ALH', 'BCF'],
  TSNE_PERPLEXITIES: [5, 10, 30, 50, 100],
  TSNE_MAX_ITER: 1000,
  N_CLUSTERS: 5,
  KMEANS_N_INIT: 10,
  RANDOM_STATE: 42,
}
